### ISSUE TITLE
How to show NFT information using Glaip?

### ISSUE THREAD

**Issue by Eunno-An** [maurovz/Glaip#18]
I succeeded login using metamask.
but I don't know how to show nft's in my wallet after login.

**Comment by maurovz** [comment]
Currently Glaip supports login functionality only. Try using Infura or Moralis API's for wallet information.

**Comment by maurovz** [comment]
If enough people let me know that this is a feature they want I could add it in the future.

**Comment by Eunno-An** [comment]
> Currently Glaip supports login functionality only. Try using Infura or Moralis API's for wallet information.

Thanks for your comment.
Can I ask you a several question about developing web3 application?

**Comment by Eunno-An** [comment]
Is there any solution keeping connections a few days?
I want to keep login , not connecting each opening app

**Comment by maurovz** [comment]
Hi @Eunno-An 

We are using the WalletConnect library so I recommend checking out their repo as they have probably answered this questions before:

https://github.com/WalletConnect/WalletConnectSwift

If you feel it's a problem in our library (Glaip), feel free open a new issue with the details. 

Cheers!
