### ISSUE TITLE
Grant Access Popup on MetaMask

### ISSUE THREAD

**Issue by AakifFRT** [maurovz/Glaip#22]
Unable to get the grant access popup on MetaMask

**Comment by mehmetdelikaya** [comment]
Hi @AakifFRT , is metamask app installed on the device?

**Comment by AakifFRT** [comment]
Yes, Version 5.14.0 It just open and don't show any popup

**Comment by CharlesBlaqk** [comment]
@AakifFRT We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by CharlesBlaqk** [comment]
@AakifFRT We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by maurovz** [comment]
@AakifFRT that is a scammer be careful. I deleted the comment.

**Comment by AakifFRT** [comment]
@maurovz did you check the issue on latest MetaMask app?

**Comment by maurovz** [comment]
> @maurovz did you check the issue on latest MetaMask app?

This sounds like a WalletConnect issue so this it's better to ask directly there: https://github.com/WalletConnect/WalletConnectSwift/

**Comment by AakifFRT** [comment]
Issue was with my internet I was using an unprotected network because of which MetaMask was not showing popups
