### ISSUE TITLE
Keep Connection Stage

### ISSUE THREAD

**Issue by Eunno-An** [maurovz/Glaip#24]
Hello @maurovz !!
Good to see you again haha!

I solve the issue.
Not third party, Not Appstorage.

Would you mind register my solution using pull request?
i want to be a contributor here.
If so, I would be very grateful.

**Comment by maurovz** [comment]
Hey! Sorry for the late reply.

 Go ahead and make a pull request and I'll review it.

**Comment by Eunno-An** [comment]
@maurovz I mentioned on my PR! Thank you so much.
