### ISSUE TITLE
How can i access public address, loginUser callback not working

### ISSUE THREAD

**Issue by dervisyilm** [maurovz/Glaip#6]
I added the glaip on my project, and call the loginUser function but, this function callback does not work,  I want to access public address
glaip.loginUser(type: .WalletConnect) { result in
              print(result)        // not work   
}
please help me

**Comment by maurovz** [comment]
Thanks for your question. Please update your package (right click, update) and add the following to your code

`.         glaip.loginUser(type: .WalletConnect) { result in
              switch result {
                case .success(let user):
                  print(user.wallet)
                case .failure(let error):
                  print(error)
              }
            }`

**Comment by maurovz** [comment]
Thanks for your question. Please update your package (right click, update) and add the following to your code

           glaip.loginUser(type: .WalletConnect) { result in
              switch result {
                case .success(let user):
                  print(user.wallet)
                case .failure(let error):
                  print(error)
              }
            }

**Comment by dervisyilm** [comment]
thank you, i access public address

**Comment by eugeniychepelev** [comment]
I have the same problem, here is my code. Help me please))

```
 let glaip = Glaip(title: "Test", description: "Test descr", supportedWallets: [.MetaMask])
        glaip.loginUser(type: .MetaMask) { result in
            switch result {
            case .success(let user):
                print(user.wallet.address)
            case .failure:
                break
            }
        }
```

**Comment by maurovz** [comment]
@eugeniychepelev your problem is that you never get a call back in either success or failure?

**Comment by eugeniychepelev** [comment]
@maurovz Yes, in any case, call back does not work

**Comment by eugeniychepelev** [comment]
@maurovz I found the reason, but I don't know why it works like this
in this method in closure self = nil
```
 public func loginUser(type: WalletType, completion: @escaping (Result<User, Error>) -> Void) {
    switch type {
    case .MetaMask:
      metaMaskLogin(completion: { [weak self] result in
        guard let self = self else { return }

        switch result {
        case let .success(user):
          DispatchQueue.main.async {
            self.userState = .loggedIn(user)
          }
          self.currentWallet = .MetaMask
          completion(.success(user))
        case let .failure(error):
          completion(.failure(error))
        }
      })
```

**Comment by maurovz** [comment]
@eugeniychepelev try installing Glaip from this branch: `bugfix/self-nil-reference`

You can switch to the branch as follow:
<img width="1046" alt="Screenshot 2022-09-19 at 13 16 58" src="https://user-images.githubusercontent.com/1994477/191006152-38f85110-97c0-4270-b151-3e2b4750461a.png">
<img width="559" alt="Screenshot 2022-09-19 at 13 17 07" src="https://user-images.githubusercontent.com/1994477/191006160-a31b0655-b1f8-4cdf-90de-4ecaed4b29ef.png">

let me know if that works. If so, I'll merge that branch into main
